<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="java_testcases.junit.NEXT_PALINDROME_TEST" tests="5" skipped="0" failures="1" errors="0" timestamp="2024-04-03T09:45:12" hostname="LAPTOP-NVVL9JFQ" time="0.714">
  <properties/>
  <testcase name="test_0" classname="java_testcases.junit.NEXT_PALINDROME_TEST" time="0.367"/>
  <testcase name="test_1" classname="java_testcases.junit.NEXT_PALINDROME_TEST" time="0.107"/>
  <testcase name="test_2" classname="java_testcases.junit.NEXT_PALINDROME_TEST" time="0.066"/>
  <testcase name="test_3" classname="java_testcases.junit.NEXT_PALINDROME_TEST" time="0.067"/>
  <testcase name="test_4" classname="java_testcases.junit.NEXT_PALINDROME_TEST" time="0.106">
    <failure message="org.junit.ComparisonFailure: expected:&lt;[1,0,0,[]1]&gt; but was:&lt;[1,0,0,[0,]1]&gt;" type="org.junit.ComparisonFailure">org.junit.ComparisonFailure: expected:&lt;[1,0,0,[]1]&gt; but was:&lt;[1,0,0,[0,]1]&gt;
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at java_testcases.junit.NEXT_PALINDROME_TEST.test_4(NEXT_PALINDROME_TEST.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
</failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
